-- sintaxe pura
SELECT P.DESCRICAO AS "Produto",
    IP.VALORUNITARIO AS "Preço"
FROM PRODUTO P
    JOIN ITEMPEDIDO IP ON P.CODPRODUTO = IP.CODPRODUTO
WHERE IP.VALORUNITARIO = (
        SELECT MAX(IP.VALORUNITARIO)
        FROM ITEMPEDIDO IP
    )
    OR IP.VALORUNITARIO = (
        SELECT MIN(IP.VALORUNITARIO)
        FROM ITEMPEDIDO IP
    )
GROUP BY P.DESCRICAO,
    IP.VALORUNITARIO;
-- sintaxe bonitinha
SELECT P.DESCRICAO AS "Produto",
    IP.VALORUNITARIO AS "Preço"
FROM PRODUTO P
    JOIN ITEMPEDIDO IP ON P.CODPRODUTO = IP.CODPRODUTO
WHERE IP.VALORUNITARIO = (
        SELECT MAX(IP2.VALORUNITARIO)
        FROM ITEMPEDIDO IP2
    )
    OR IP.VALORUNITARIO = (
        SELECT MIN(IP3.VALORUNITARIO)
        FROM ITEMPEDIDO IP3
    )
GROUP BY P.DESCRICAO,
    IP.VALORUNITARIO;