CREATE TABLE EMPREGADO (
    Ident INT PRIMARY KEY,
    Nome VARCHAR(50),
    Sal DECIMAL(10, 2),
End VARCHAR(100),
Sexo CHAR(1),
DataNasc DATE,
DepNum INT REFERENCES DEPARTAMENTO(Num),
SuperIdent INT REFERENCES EMPREGADO(Ident)
);
CREATE TABLE DEPARTAMENTO (
    Num INT PRIMARY KEY,
    Nome VARCHAR(50),
    IdentGer INT REFERENCES EMPREGADO(Ident),
    DataIni DATE
);
CREATE TABLE PROJETO (
    Num INT PRIMARY KEY,
    Nome VARCHAR(50),
    Local VARCHAR(100),
    DepNum INT REFERENCES DEPARTAMENTO(Num)
);
CREATE TABLE TRABALHANDO (
    IdentEmp INT REFERENCES EMPREGADO(Ident),
    ProjNum INT REFERENCES PROJETO(Num),
    HRS INT,
    PRIMARY KEY (IdentEmp, ProjNum)
);
CREATE TABLE DEPENDENTE (
    IdentEmp INT REFERENCES EMPREGADO(Ident),
    Nome VARCHAR(50),
    Sexo CHAR(1),
    DataNasc DATE,
    Parentesco VARCHAR(20),
    PRIMARY KEY (IdentEmp, Nome)
);
CREATE TABLE DEPLOC (
    DepNum INT REFERENCES DEPARTAMENTO(Num),
    Local VARCHAR(100),
    PRIMARY KEY (DepNum, Local)
);
SELECT PROJETO.Num,
    PROJETO.DepNum
FROM PROJETO;
SELECT EMPREGADO.Ident,
    EMPREGADO.Nome,
    DEPENDENTE.Nome,
    DEPENDENTE.Parentesco
FROM EMPREGADO
    INNER JOIN DEPENDENTE ON EMPREGADO.Ident = DEPENDENTE.IdentEmp;
SELECT E1.Nome,
    E1.Sexo,
    E2.Ident,
    E2.Nome
FROM EMPREGADO E1
    LEFT JOIN EMPREGADO E2 ON E1.SuperIdent = E2.Ident;
SELECT DISTINCT Sal
FROM EMPREGADO;
SELECT EMPREGADO.Nome
FROM EMPREGADO
    LEFT JOIN DEPENDENTE ON EMPREGADO.Ident = DEPENDENTE.IdentEmp
WHERE DEPENDENTE.IdentEmp IS NULL;
SELECT EMPREGADO.Nome
FROM EMPREGADO
    INNER JOIN ENDERECO ON EMPREGADO.
End = ENDERECO.Endereco
INNER JOIN CIDADE ON ENDERECO.Cidade = CIDADE.Cidade
WHERE CIDADE.Nome LIKE '%Salvador%';
SELECT EMPREGADO.Nome,
    EMPREGADO.Sal * 1.1
FROM EMPREGADO
    INNER JOIN TRABALHANDO ON EMPREGADO.Ident = TRABALHANDO.IdentEmp
    INNER JOIN PROJETO ON TRABALHANDO.ProjNum = PROJETO.Num
WHERE PROJETO.Nome = 'Reengenharia';
SELECT EMPREGADO.Nome
FROM EMPREGADO
    LEFT JOIN EMPREGADO E ON EMPREGADO.SuperIdent = E.Ident
WHERE E.Ident IS NULL;
SELECT DISTINCT Local
FROM (
        SELECT Local
        FROM PROJETO
        UNION
        SELECT Local
        FROM DEPLOC
    ) AS Locais;
SELECT EMPREGADO.Nome
FROM EMPREGADO
    INNER JOIN TRABALHANDO ON EMPREGADO.Ident = TRABALHANDO.IdentEmp
WHERE TRABALHANDO.HRS < 20;